function cfg = lc0NDConfig()
%LC0NDCONFIG Source and calibration settings for the LC0 prototype.
%   This configuration deliberately contains no fitted target-tire Fx or
%   combined-slip coefficients: Round 8 LC0 data is free rolling only.

packageRoot = fileparts(mfilename('fullpath'));
magicFormulaRoot = fileparts(fileparts(packageRoot));
cfg = struct();
cfg.target = struct( ...
    'runDirectory',fullfile(magicFormulaRoot,'TTC Documentation', ...
        'Round 8 (16 in Hoosiers)', ...
        'RunData_Cornering_Matlab_USCS_10inch_Round8'), ...
    'runIds',[15 16 18 19], ...
    'filePrefix','A1965run', ...
    'maxAbsSlip',1e-3, ...
    'description','Hoosier 16x7.5-10 LC0, 8 in rim; free rolling');
cfg.reference = struct('load_N',200*4.4482216152605, ...
    'pressure_psi',12,'camber_deg',0);
cfg.calibration = struct('rhoMu',1,'rhoStiff',1,'couplingExponent',1.3);
cfg.targetForceFit = struct('load_N',200*4.4482216152605, ...
    'loadHalfWidth_N',20*4.4482216152605, ...
    'pressure_psi',12,'pressureHalfWidth_psi',0.8, ...
    'camber_deg',0,'camberHalfWidth_deg',0.4, ...
    'maxAbsSlipRatio',0.001,'alphaGrid',(-12:0.25:12)', ...
    'alphaHalfWidth_deg',0.15,'minSamplesPerBin',15);
cfg.donor = struct( ...
    'file',fullfile(magicFormulaRoot,'TTC Documentation', ...
        'Round 6 (18 in Hoosiers)', ...
        'RunData_10inch_DriveBrake_Matlab_USCS','A1654run47.mat'), ...
    'description',['Provisional LC0 donor: Hoosier 18x6-10 LC0 C2000, ' ...
        '7 in rim, TTC Round 6 run 47.']);
cfg.donorFit = struct('load_N',200*4.4482216152605, ...
    'loadHalfWidth_N',20*4.4482216152605, ...
    'pressure_psi',12,'pressureHalfWidth_psi',0.8, ...
    'camber_deg',0,'camberHalfWidth_deg',0.4, ...
    'maxAbsSlipAngle_deg',0.4, ...
    'kappaGrid',(-0.16:0.005:0.16)', ...
    'kappaHalfWidth',0.003,'minSamplesPerBin',15);
cfg.donorLateral = struct( ...
    'file',fullfile(magicFormulaRoot,'TTC Documentation', ...
        'Round 6 (18 in Hoosiers)', ...
        'RunData_10inch_DriveBrake_Matlab_USCS','A1654run46.mat'), ...
    'description',['Paired free-rolling donor: Hoosier 18x6-10 LC0 C2000, ' ...
        '7 in rim, TTC Round 6 run 46.']);
couplingReference = struct('load_N',200*4.4482216152605, ...
    'loadHalfWidth_N',75*4.4482216152605, ...
    'pressure_psi',12,'pressureHalfWidth_psi',0.8, ...
    'camber_deg',0,'camberHalfWidth_deg',0.4);
cfg.couplingLongitudinalFit = couplingReference;
cfg.couplingLongitudinalFit.maxAbsSlipAngle_deg = 0.5;
cfg.couplingLongitudinalFit.kappaGrid = (-0.16:0.01:0.16)';
cfg.couplingLongitudinalFit.kappaHalfWidth = 0.006;
cfg.couplingLongitudinalFit.minSamplesPerBin = 15;
cfg.couplingLateralFit = couplingReference;
cfg.couplingLateralFit.maxAbsSlipRatio = 0.003;
cfg.couplingLateralFit.alphaGrid = (-13:0.5:13)';
cfg.couplingLateralFit.alphaHalfWidth_deg = 0.3;
cfg.couplingLateralFit.minSamplesPerBin = 15;
cfg.couplingFit = couplingReference;
cfg.couplingFit.minAbsSlipRatio = 0.02;
cfg.couplingFit.minAbsSlipAngle_deg = 0.5;
cfg.couplingFit.pGrid = (1:0.05:4)';
cfg.couplingFit.minPoints = 500;
cfg.outputDirectory = fullfile(packageRoot,'results');
end
