function fit = lc0NDFitTargetScaling(data,opts,referenceFit)
%LC0NDFITTARGETSCALING Fit measured target-tire load/pressure/camber scales.
%   The reference alpha curve remains the measured target curve. This fit
%   adds bounded capacity and small-slip-stiffness corrections from the
%   other exact-size target TTC bins.

required = {'loadCenters_N','loadHalfWidth_N','pressureCenters_psi', ...
    'pressureHalfWidth_psi','camberCenters_deg','camberHalfWidth_deg', ...
    'smallSlipWindow_deg','reference_load_N','reference_pressure_psi', ...
    'reference_camber_deg'};
if ~isstruct(opts) || ~isscalar(opts) || ~all(isfield(opts,required))
    error('lc0NDFitTargetScaling:badOptions', ...
        'Options must contain the target scaling bin and reference fields.');
end
if nargin < 3 || isempty(referenceFit), referenceFit = struct(); end

summaryOpts = opts;
summary = lc0NDLateralSummary(data,summaryOpts);
valid = summary.is_complete_sweep & isfinite(summary.peak_mu_y) & ...
    summary.peak_mu_y > 0 & isfinite(summary.stiffness_N_per_deg) & ...
    summary.stiffness_N_per_deg > 0;
if ~any(valid)
    error('lc0NDFitTargetScaling:noQualifiedBins', ...
        'Target TTC data has no complete positive lateral bins.');
end

distance = inf(height(summary),1);
distance(valid) = normalizedDistance(summary.load_center_N(valid), ...
    opts.reference_load_N,opts.loadHalfWidth_N) + ...
    normalizedDistance(summary.pressure_center_psi(valid), ...
    opts.reference_pressure_psi,max(opts.pressureHalfWidth_psi,eps)) + ...
    normalizedDistance(summary.camber_center_deg(valid), ...
    opts.reference_camber_deg,max(opts.camberHalfWidth_deg,eps));
[~,referenceIndex] = min(distance);
referencePeak = getField(referenceFit,'peak_abs_mu_y', ...
    summary.peak_mu_y(referenceIndex));
referenceStiffness = getField(referenceFit,'stiffness_N_per_deg', ...
    summary.stiffness_N_per_deg(referenceIndex));
referenceLoad = getField(referenceFit,'stiffness_reference_load_N', ...
    summary.mean_Fz_N(referenceIndex));
if ~isscalar(referencePeak) || ~isfinite(referencePeak) || referencePeak <= 0 || ...
        ~isscalar(referenceStiffness) || ~isfinite(referenceStiffness) || ...
        referenceStiffness <= 0 || ~isscalar(referenceLoad) || ...
        ~isfinite(referenceLoad) || referenceLoad <= 0
    error('lc0NDFitTargetScaling:badReference', ...
        'Reference fit must contain positive finite peak and stiffness.');
end

tableData = summary;
tableData.mu_scale = summary.peak_mu_y./referencePeak;
% Cornering stiffness is a force slope, so its absolute value grows with
% normal load even when the tire's nondimensional response is unchanged.
% Normalize both the measured and reference slopes by their measured load
% before forming the transfer factor.
tableData.stiffness_scale = (summary.stiffness_N_per_deg./summary.mean_Fz_N) ./ ...
    (referenceStiffness/referenceLoad);
tableData.is_qualified = valid;
reference = struct('load_N',opts.reference_load_N, ...
    'pressure_psi',opts.reference_pressure_psi, ...
    'camber_deg',opts.reference_camber_deg, ...
    'peak_mu_y',referencePeak, ...
    'stiffness_N_per_deg',referenceStiffness, ...
    'stiffness_reference_load_N',referenceLoad, ...
    'mu_scale',1,'stiffness_scale',1);
fit = struct('options',opts,'summary',summary,'table',tableData, ...
    'reference',reference,'is_qualified',any(valid));
end

function value = normalizedDistance(value,center,halfWidth)
value = abs(value-center)./max(halfWidth,eps);
end

function value = getField(s,name,defaultValue)
if isstruct(s) && isfield(s,name) && ~isempty(s.(name))
    value = s.(name);
else
    value = defaultValue;
end
end
