function scenarios = lc0NDUncertaintyScenarios(calibration,bounds)
%LC0NDUNCERTAINTYSCENARIOS Build explicit donor-transfer cases.
%   The target tire has no measured longitudinal or combined-slip surface.
%   These cases keep that uncertainty visible instead of presenting donor
%   force levels as exact target-tire measurements.

if nargin < 1 || ~isstruct(calibration) || ~isscalar(calibration)
    error('lc0NDUncertaintyScenarios:badCalibration', ...
        'CALIBRATION must be a scalar struct.');
end
required = {'rhoMu','rhoStiff','couplingExponent'};
if ~all(isfield(calibration,required))
    error('lc0NDUncertaintyScenarios:missingCalibration', ...
        'CALIBRATION requires rhoMu, rhoStiff, and couplingExponent.');
end
if any(~isfinite([calibration.rhoMu,calibration.rhoStiff, ...
        calibration.couplingExponent])) || calibration.rhoMu <= 0 || ...
        calibration.rhoStiff <= 0 || calibration.couplingExponent < 1
    error('lc0NDUncertaintyScenarios:badCalibration', ...
        'Calibration scales must be finite and positive; exponent must be >= 1.');
end

defaults = struct( ...
    'rhoMuLow',0.90,'rhoMuHigh',1.10, ...
    'rhoStiffLow',0.85,'rhoStiffHigh',1.15, ...
    'couplingExponentLow',max(1,calibration.couplingExponent-0.30), ...
    'couplingExponentHigh',calibration.couplingExponent+0.30);
if nargin >= 2 && ~isempty(bounds)
    names = fieldnames(defaults);
    if ~isstruct(bounds) || ~isscalar(bounds)
        error('lc0NDUncertaintyScenarios:badBounds', ...
            'BOUNDS must be a scalar struct.');
    end
    for i = 1:numel(names)
        if isfield(bounds,names{i})
            defaults.(names{i}) = bounds.(names{i});
        end
    end
end
values = [defaults.rhoMuLow,calibration.rhoMu,defaults.rhoMuHigh, ...
    defaults.rhoStiffLow,calibration.rhoStiff,defaults.rhoStiffHigh, ...
    defaults.couplingExponentLow,calibration.couplingExponent, ...
    defaults.couplingExponentHigh];
if any(~isfinite(values)) || any(values([1 2 3 4 5 6]) <= 0) || ...
        any(values([7 8 9]) < 1) || defaults.rhoMuLow > calibration.rhoMu || ...
        defaults.rhoMuHigh < calibration.rhoMu || ...
        defaults.rhoStiffLow > calibration.rhoStiff || ...
        defaults.rhoStiffHigh < calibration.rhoStiff || ...
        defaults.couplingExponentLow > calibration.couplingExponent || ...
        defaults.couplingExponentHigh < calibration.couplingExponent
    error('lc0NDUncertaintyScenarios:badBounds', ...
        'Uncertainty bounds must contain the nominal calibration in order.');
end

scenarios = struct( ...
    'name',{'low','nominal','high'}, ...
    'rhoMu',{defaults.rhoMuLow,calibration.rhoMu,defaults.rhoMuHigh}, ...
    'rhoStiff',{defaults.rhoStiffLow,calibration.rhoStiff,defaults.rhoStiffHigh}, ...
    'couplingExponent',{defaults.couplingExponentLow, ...
        calibration.couplingExponent,defaults.couplingExponentHigh}, ...
    'source',{'bounded donor transfer','nominal donor transfer', ...
        'bounded donor transfer'});
end
