function model = lc0NDBuildModel(targetLateral,donorLongitudinal,donorLateral,calibration)
%LC0NDBUILDMODEL Assemble an explicit target/donor nondimensional model.
%   Target lateral force is retained from measured 16-inch LC0 data. The
%   provisional donor supplies only longitudinal shape and coupling context.

requiredCalibration = {'rhoMu','rhoStiff','couplingExponent'};
for i = 1:numel(requiredCalibration)
    if ~isfield(calibration,requiredCalibration{i})
        error('lc0NDBuildModel:missingCalibration', ...
            'CALIBRATION must contain %s.',requiredCalibration{i});
    end
end
if calibration.rhoMu <= 0 || calibration.rhoStiff <= 0 || ...
        calibration.couplingExponent < 1
    error('lc0NDBuildModel:badCalibration', ...
        'rhoMu/rhoStiff must be positive and couplingExponent must be >= 1.');
end
checkLateral(targetLateral,'targetLateral');
checkLateral(donorLateral,'donorLateral');
if ~isfield(donorLongitudinal,'curve') || ...
        ~all(ismember({'slip_ratio','mu_x','is_qualified'}, ...
        donorLongitudinal.curve.Properties.VariableNames))
    error('lc0NDBuildModel:badLongitudinal', ...
        'DONORLONGITUDINAL must contain a qualified mu_x curve.');
end

targetPeak = max(abs(targetLateral.curve.mu_y(targetLateral.curve.is_qualified)));
donorLateralPeak = max(abs(donorLateral.curve.mu_y(donorLateral.curve.is_qualified)));
if ~isfinite(targetPeak) || ~isfinite(donorLateralPeak) || donorLateralPeak <= 0
    error('lc0NDBuildModel:badCapacity','Qualified lateral curves require nonzero peaks.');
end
model = struct('target_lateral',targetLateral, ...
    'donor_longitudinal',donorLongitudinal, ...
    'donor_lateral',donorLateral, ...
    'rho_mu',calibration.rhoMu, ...
    'rho_stiff',calibration.rhoStiff, ...
    'coupling_exponent',calibration.couplingExponent, ...
    'longitudinal_mu_scale',calibration.rhoMu*targetPeak/donorLateralPeak, ...
    'target_lateral_capacity',targetPeak);
end

function checkLateral(fit,name)
if ~isfield(fit,'curve') || ...
        ~all(ismember({'slip_angle_deg','mu_y','is_qualified'}, ...
        fit.curve.Properties.VariableNames))
    error('lc0NDBuildModel:badLateral', ...
        '%s must contain a qualified mu_y curve.',name);
end
end
