function tests = test_lc0NDFitTargetScaling
tests = functiontests(localfunctions);
end
function testBuildsLoadNormalizedCapacityAndStiffnessScales(testCase)
% Break caught: the exact-size lateral data is reduced to one reference
% point, so load dependence is lost in the vehicle model.
addpath(fileparts(fileparts(mfilename('fullpath'))));
data = struct( ...
    'slipAngle_deg',[-1;0;1;-1;0;1], ...
    'Fy_N',[-100;0;100;-180;0;180], ...
    'Fz_N',[100;100;100;200;200;200], ...
    'pressure_psi',12*ones(6,1), ...
    'camber_deg',zeros(6,1));
opts = struct('loadCenters_N',[100;200],'loadHalfWidth_N',1, ...
    'pressureCenters_psi',12,'pressureHalfWidth_psi',0.1, ...
    'camberCenters_deg',0,'camberHalfWidth_deg',0.1, ...
    'smallSlipWindow_deg',1,'minSamples',1,'minSlipAngleSpan_deg',2, ...
    'reference_load_N',100,'reference_pressure_psi',12, ...
    'reference_camber_deg',0);
reference = struct('peak_abs_mu_y',1);

fit = lc0NDFitTargetScaling(data,opts,reference);

row = fit.table(fit.table.load_center_N == 200,:);
verifyEqual(testCase,row.mu_scale,0.9,'AbsTol',1e-12);
verifyEqual(testCase,fit.reference.mu_scale,1,'AbsTol',1e-12);
verifyEqual(testCase,row.stiffness_scale,0.9,'AbsTol',1e-12);
end
