function options = ggProductionOptions()
%GGPRODUCTIONOPTIONS Shared full-resolution G-G settings for production runs.

options = struct( ...
    'fastScreening',false, ...
    'continuation',false, ...
    'maxVelocity',28);
end
