function evaluator = steadyStateEvaluator(car)
%STEADYSTATEEVALUATOR Cache one exact vehicle-equation evaluation.
%   FMINCON commonly asks the objective and nonlinear constraints about the
%   same state in sequence. Reusing that exact result avoids solving the
%   coupled ride-height/aeromap system twice without approximating it.

lastP = [];
lastState = struct();
lastFullState = struct();
lastRideHeightContext = [];
equationCallCount = 0;

evaluator = struct('evaluate',@evaluate,'evaluateFull',@evaluateFull, ...
    'equationCalls',@equationCalls);

    function state = evaluate(P)
        P = P(:).';
        if isempty(lastP) || ~isequal(P,lastP)
            [engineRpm,beta,latAccel,longAccel,yawAccel,wheelAccel,omega, ...
                currentGear,Fzvirtual,Fz,alpha,T,Fy,gamma,Fx,ssInfo, ...
                lastRideHeightContext] = ...
                    car.equations(P,lastRideHeightContext, ...
                    struct('qssValidityOnly',true));
            lastP = P;
            equationCallCount = equationCallCount + 1;
            lastState = struct('engineRpm',engineRpm,'beta',beta, ...
                'latAccel',latAccel,'longAccel',longAccel, ...
                'yawAccel',yawAccel,'wheelAccel',wheelAccel, ...
                'Fzvirtual',Fzvirtual,'redline',car.powertrain.redline, ...
                'ssInfo',ssInfo, ...
                'rideHeightContext',lastRideHeightContext, ...
                'aeroConverged',diagnosticValue(ssInfo,'aero_converged',true), ...
                'aeroOutsideMap',diagnosticValue(ssInfo,'aero_outside_map',false), ...
                'aeroCoverageValid',diagnosticValue(ssInfo,'aero_coverage_valid',true), ...
                'aeroResidualIn',diagnosticValue(ssInfo,'aero_residual_in',0), ...
                'aeroResidualToleranceIn',car.qssAeroResidualToleranceIn);
            lastFullState = struct('engineRpm',engineRpm,'beta',beta, ...
                'latAccel',latAccel,'longAccel',longAccel, ...
                'yawAccel',yawAccel,'wheelAccel',wheelAccel, ...
                'omega',omega,'currentGear',currentGear, ...
                'Fzvirtual',Fzvirtual,'Fz',Fz,'alpha',alpha,'T',T, ...
                'Fy',Fy,'gamma',gamma,'Fx',Fx,'ssInfo',ssInfo, ...
                'rideHeightContext',lastRideHeightContext);
        end
        state = lastState;
    end

    function state = evaluateFull(P)
        % evaluate() already requests every Car.equations output. Expose the
        % cached full tuple so result assembly does not solve the same state a
        % second time after fmincon returns.
        evaluate(P);
        state = lastFullState;
    end

    function count = equationCalls()
        count = equationCallCount;
    end
end

function value = diagnosticValue(diagnostics,name,defaultValue)
if isstruct(diagnostics) && isfield(diagnostics,name) && ...
        ~isempty(diagnostics.(name))
    value = diagnostics.(name);
else
    value = defaultValue;
end
end
