function tests = test_rampSpeedSchema
tests = functiontests(localfunctions);
end
function testCreatesVersionedLateralRun(testCase)
fixture = makeRampFixture(); %#ok<NASGU>
run = rampSpeed.makeRun("lateral","coast",struct("speeds",[5 10]), ...
    struct("id","baseline","label","baseline","carRole","lap"));

verifyEqual(testCase,run.schemaVersion,1);
verifyEqual(testCase,run.caseId,"baseline");
verifyEqual(testCase,run.type,"lateral");
verifyEqual(testCase,run.mode,"coast");
verifyEqual(testCase,run.status,"pending");
verifyTrue(testCase,all(ismember(["perSpeed","points","runMeta", ...
    "status","raw"],string(fieldnames(run)))));
verifyEqual(testCase,height(run.perSpeed),2);
verifyTrue(testCase,all(ismember(["speed_mps","valid","status", ...
    "aLat_free_mps2","aLat_sustainable_mps2", ...
    "mechanical_balance_front","aero_balance_front"], ...
    string(run.perSpeed.Properties.VariableNames))));
verifyTrue(testCase,all(isnan(run.perSpeed.front_ride_height_m)));
verifyTrue(testCase,run.runMeta.lateralMetricsApplicable);
end

function testLongitudinalOnlyFieldsAreUnavailable(testCase)
run = rampSpeed.makeRun("longitudinal","",struct("speeds",5), ...
    struct("id","accel","label","accel","carRole","acceleration"));

verifyFalse(testCase,run.runMeta.lateralMetricsApplicable);
verifyTrue(testCase,all(isnan(run.perSpeed.K_linear_rad_per_mps2)));
verifyTrue(testCase,all(isnan(run.perSpeed.mechanical_balance_front)));
verifyTrue(testCase,all(isnan(run.perSpeed.aero_balance_front)));
verifyFalse(testCase,run.perSpeed.lateral_metrics_applicable(1));
end

function testMakeStudyCreatesVersionedContainer(testCase)
study = rampSpeed.makeStudy("test-app");

verifyEqual(testCase,study.schemaVersion,1);
verifyEqual(testCase,study.appVersion,"test-app");
verifyTrue(testCase,isdatetime(study.created));
verifyTrue(testCase,isempty(study.cases));
verifyTrue(testCase,isempty(study.runs));
verifyTrue(testCase,isfield(study,"displayUnits"));
end

function testDisplayConversionDoesNotMutateInput(testCase)
values = [1 2];
displayed = rampSpeed.displayUnits(values,"m","ft");

verifyEqual(testCase,displayed,values/0.3048,"AbsTol",1e-12);
verifyEqual(testCase,values,[1 2]);
end

function testSchemaTopLevelAndColumnTypesAreExact(testCase)
run = rampSpeed.makeRun("lateral","coast",struct("speeds",[5 10]), ...
    struct("id","baseline","label","baseline","carRole","lap"));

verifyEqual(testCase,string(fieldnames(run)), ...
    ["schemaVersion";"caseId";"type";"mode";"settings"; ...
    "perSpeed";"points";"runMeta";"status";"raw"]);
verifyEqual(testCase,class(run.perSpeed.speed_mps),'double');
verifyTrue(testCase,islogical(run.perSpeed.valid));
verifyTrue(testCase,isstring(run.perSpeed.status));
verifyTrue(testCase,isstring(run.perSpeed.reason));
verifyEqual(testCase,class(run.points.speed_mps),'double');
verifyTrue(testCase,islogical(run.points.valid));
verifyTrue(testCase,isstring(run.points.status));

expectedPerSpeed = string({ ...
    'speed_mps','valid','status','reason','aLat_mps2','aLong_mps2', ...
    'engine_rpm','current_gear','throttle','downforce_N','drag_N','ClA_m2', ...
    'CdA_m2','LoD','aero_balance_front','aero_outside_map','aero_residual_m', ...
    'Fz_front_axle_N','Fz_rear_axle_N','min_Fz_N','wheel_lift','LLTD', ...
    'LLT_front_N','LLT_rear_N','long_load_transfer_N','aLat_free_mps2', ...
    'aLat_sustainable_mps2','ramp_complete_fraction','truncated', ...
    'power_limited','K_linear_rad_per_mps2','K_linear_r2', ...
    'K_at_limit_rad_per_mps2','cuo_steer_linear_rad','cuo_steer_limit_rad', ...
    'mechanical_balance_front','grip_balance_mid','grip_balance_limit', ...
    'alpha_balance_mid_rad','alpha_balance_limit_rad','LLT_norm_balance_mid', ...
    'LLT_norm_balance_limit','front_Fz_fraction_mid','front_Fz_fraction_limit', ...
    'front_downforce_N','rear_downforce_N','front_ride_height_m', ...
    'rear_ride_height_m','pitch_rad','front_shock_travel_m', ...
    'rear_shock_travel_m','front_camber_rad','rear_camber_rad', ...
    'min_Fz_limit_N','max_constraint_residual','n_exitflag1','n_exitflag2', ...
    'aLong_max_mps2','aLat_achieved_mps2','aLat_force_residual_mps2', ...
    'pure_ay0','steer_zero','lat_velocity_zero','yaw_rate_zero', ...
    'rear_slip_ratio','throttle_upper_active','rear_slip_upper_active', ...
    'traction_limited','lateral_metrics_applicable'});
verifyEqual(testCase,string(run.perSpeed.Properties.VariableNames),expectedPerSpeed);

expectedPoints = string({ ...
    'speed_mps','speed_index','point_index','valid','status','exitflag', ...
    'max_constraint_residual','max_equality_residual', ...
    'max_inequality_violation','aLat_mps2','aLong_mps2','steer_rad', ...
    'lat_velocity_mps','yaw_rate_rps','engine_rpm','current_gear','throttle', ...
    'downforce_N','drag_N','ClA_m2','CdA_m2','LoD','aero_balance_front', ...
    'aero_outside_map','aero_residual_m','Fz_front_axle_N','Fz_rear_axle_N', ...
    'min_Fz_N','wheel_lift','LLTD','LLT_front_N','LLT_rear_N', ...
    'long_load_transfer_N','aLong_max_mps2','aLat_achieved_mps2', ...
    'aLat_force_residual_mps2','pure_ay0','steer_zero','lat_velocity_zero', ...
    'yaw_rate_zero','lateral_metrics_applicable','Fz_FL_N','Fz_FR_N', ...
    'Fz_RL_N','Fz_RR_N','Fx_FL_N','Fx_FR_N','Fx_RL_N','Fx_RR_N', ...
    'Fy_FL_N','Fy_FR_N','Fy_RL_N','Fy_RR_N','alpha_FL_rad','alpha_FR_rad', ...
    'alpha_RL_rad','alpha_RR_rad','gamma_FL_rad','gamma_FR_rad', ...
    'gamma_RL_rad','gamma_RR_rad','kappa_FL','kappa_FR','kappa_RL', ...
    'kappa_RR','T_FL_Nm','T_FR_Nm','T_RL_Nm','T_RR_Nm','omega_FL_rps', ...
    'omega_FR_rps','omega_RL_rps','omega_RR_rps'});
verifyEqual(testCase,string(run.points.Properties.VariableNames),expectedPoints);

fixture = makeRampFixture();
verifyTrue(testCase,isfield(fixture,"lateralRun"));
verifyTrue(testCase,isfield(fixture,"longitudinalRun"));
verifyFalse(testCase,fixture.longitudinalRun.runMeta.lateralMetricsApplicable);
verifyTrue(testCase,all(fixture.longitudinalRun.perSpeed.pure_ay0));
verifyTrue(testCase,all(fixture.longitudinalRun.perSpeed.steer_zero));
end

function testLongitudinalAvailabilityIsExplicit(testCase)
run = rampSpeed.makeRun("longitudinal","",struct("speeds",5), ...
    struct("id","accel","label","accel","carRole","acceleration"));

verifyFalse(testCase,run.runMeta.lateralMetricsApplicable);
verifyFalse(testCase,run.perSpeed.lateral_metrics_applicable(1));
verifyTrue(testCase,isnan(run.perSpeed.aLat_free_mps2(1)));
verifyTrue(testCase,isnan(run.perSpeed.K_linear_rad_per_mps2(1)));
verifyTrue(testCase,isnan(run.perSpeed.mechanical_balance_front(1)));
end
