function tests = test_rampSweepAdditionalMetrics
tests = functiontests(localfunctions);
end

function testPerSpeedStoresAxleAeroRideHeightAndCamber(testCase)
[cars,~] = carConfig();
R = rampSweep(cars{1,1},struct('speeds',5,'nRamp',3,'nBisect',0, ...
    'mode','coast','verbose',false));
S = R.perSpeed;
names = {'aero_downforce_front_N','aero_downforce_rear_N', ...
    'front_ride_height_in','rear_ride_height_in', ...
    'front_camber_deg','rear_camber_deg','pitch_angle_deg', ...
    'front_shock_travel_in','rear_shock_travel_in'};

verifyTrue(testCase,all(ismember(names,S.Properties.VariableNames)));
verifyEqual(testCase,S.aero_downforce_front_N + S.aero_downforce_rear_N, ...
    S.downforce,'AbsTol',1e-9);
verifyGreaterThan(testCase,S.front_camber_deg,0);
verifyGreaterThan(testCase,S.rear_camber_deg,0);
verifyEqual(testCase,S.pitch_angle_deg,atan2d( ...
    (S.front_ride_height_in-S.rear_ride_height_in)*0.0254,cars{1,1}.W_b), ...
    'AbsTol',1e-12);
verifyEqual(testCase,S.front_shock_travel_in, ...
    (cars{1,1}.rideHeightAero.static_front_ride_height_in-S.front_ride_height_in) ...
    *cars{1,1}.rideHeightAero.motion_ratio_front,'AbsTol',1e-12);
verifyEqual(testCase,S.rear_shock_travel_in, ...
    (cars{1,1}.rideHeightAero.static_rear_ride_height_in-S.rear_ride_height_in) ...
    *cars{1,1}.rideHeightAero.motion_ratio_rear,'AbsTol',1e-12);
end
