function car = buildCarFromSpec_pm(spec)
    tireMu = tire_pm( ...
        spec.mu_model_coeff, ...
        spec.mu_model_exp, ...
        spec.track_friction_scale);

    ptrain = powertrain_pm( ...
        spec.gears, ...
        spec.final_drive, ...
        spec.eta_driveline, ...
        spec.wheel_radius, ...
        spec.rpm_redline, ...
        spec.rpm_idle, ...
        spec.rpm_vec, ...
        spec.tq_lbft_vec);

    carParams = struct( ...
        'm',                 spec.m, ...
        'cda',               spec.cda, ...
        'cla',               spec.cla, ...
        'cop',               spec.cop, ...
        'weight_r',          spec.weight_r, ...
        'wheel_radius',      spec.wheel_radius, ...
        'rho',               spec.rho, ...
        'g',                 spec.g, ...
        'c_roll',            spec.c_roll, ...
        'max_brake_torque',  spec.max_brake_torque, ...
        'tire_limited_brake',spec.tire_limited_brake);

    car = car_pm(carParams, tireMu, ptrain);
end
