function catalog = aeroMapCatalog()
%AEROMAPCATALOG Return the project-owned ramp-speed aero-map definitions.
%   Setup specifications store only the ID. Paths are resolved here so the
%   app and saved studies remain portable within the project checkout.

root = fileparts(fileparts(mfilename('fullpath')));
catalog = struct( ...
    'id',"b26", ...
    'label',"B26", ...
    'relativePath',"aeromap_b26.csv", ...
    'path',string(fullfile(root,'aeromap_b26.csv')));
end
