function derived = deriveRollStiffness(frontSpringRate_lb_in,rearSpringRate_lb_in, ...
    motionRatioFront,motionRatioRear,track_m,frontArbStiffness_NmPerRad, ...
    rearArbStiffness_NmPerRad)
%DERIVEROLLSTIFFNESS Derive ramp-speed roll split from editable setup rates.

values = [frontSpringRate_lb_in,rearSpringRate_lb_in,motionRatioFront, ...
    motionRatioRear,track_m,frontArbStiffness_NmPerRad, ...
    rearArbStiffness_NmPerRad];
if any(~isfinite(double(values))) || any(double(values) < 0) || ...
        track_m <= 0 || motionRatioFront <= 0 || motionRatioRear <= 0
    error('rampSpeed:invalidRollStiffnessInput', ...
        'Spring, motion-ratio, track, and ARB inputs must be physical finite values.');
end

lbInToNpm = 175.126835;
wheelRateFront = frontSpringRate_lb_in*lbInToNpm*motionRatioFront^2;
wheelRateRear = rearSpringRate_lb_in*lbInToNpm*motionRatioRear^2;
springRollFront = wheelRateFront*track_m^2/2;
springRollRear = wheelRateRear*track_m^2/2;
frontTotal = springRollFront + frontArbStiffness_NmPerRad;
rearTotal = springRollRear + rearArbStiffness_NmPerRad;
if frontTotal <= 0 || rearTotal <= 0
    error('rampSpeed:invalidRollStiffness', ...
        'Front and rear total roll stiffness must both be positive.');
end

derived = struct( ...
    'wheelRateFront_Npm',wheelRateFront, ...
    'wheelRateRear_Npm',wheelRateRear, ...
    'springRollStiffnessFront_NmPerRad',springRollFront, ...
    'springRollStiffnessRear_NmPerRad',springRollRear, ...
    'frontRollStiffness_NmPerRad',frontTotal, ...
    'rearRollStiffness_NmPerRad',rearTotal, ...
    'R_sf',frontTotal/(frontTotal+rearTotal));
end
