function presets = fixedSpeedPresets()
%FIXEDSPEEDPRESETS Return the supported deterministic ramp speed grids.

presets = struct( ...
    'id',{"preview","accurate","highAccuracy"}, ...
    'label',{"Preview","Accurate","High accuracy"}, ...
    'pointCount',{5,11,21}, ...
    'fixed',{true,true,true});
end
