function catalog = metricCatalog(options)
%METRICCATALOG Describe the metrics exposed by the ramp-speed UI.

if nargin < 1 || isempty(options)
    options = struct();
end

catalog = repmat(metricTemplate(),0,1);

catalog(end+1) = makeMetric("capability_free","capability","lateral", ...
    "perSpeed","aLat_free_mps2",[],"m/s^2","g",1/9.80665, ...
    "a_y free (g)","Free lateral capability","",false,"line",@validRows);
catalog(end+1) = makeMetric("capability_sustainable","capability","lateral", ...
    "perSpeed","aLat_sustainable_mps2",[],"m/s^2","g",1/9.80665, ...
    "a_y sustainable (g)","Sustainable lateral capability","",false,"line",@validRows);
catalog(end+1) = makeMetric("ramp_complete","capability",["lateral","longitudinal"], ...
    "perSpeed","ramp_complete_fraction",[],"fraction","%",100, ...
    "ramp completion (%)","Ramp completion","",false,"line",@validRows);

catalog(end+1) = makeMetric("aero_front_load","aero",["lateral","longitudinal"], ...
    "perSpeed","front_downforce_N",[],"N","N",1, ...
    "front aero load (N)","Aerodynamic load","Front axle",false,"line",@validRows);
catalog(end+1) = makeMetric("aero_rear_load","aero",["lateral","longitudinal"], ...
    "perSpeed","rear_downforce_N",[],"N","N",1, ...
    "rear aero load (N)","Aerodynamic load","Rear axle",false,"line",@validRows);
catalog(end+1) = makeMetric("downforce","aero",["lateral","longitudinal"], ...
    "perSpeed","downforce_N",[],"N","N",1, ...
    "downforce (N)","Aerodynamic load","Total",false,"line",@validRows);
catalog(end+1) = makeMetric("drag","aero",["lateral","longitudinal"], ...
    "perSpeed","drag_N",[],"N","N",1, ...
    "drag (N)","Aerodynamic load","Total",false,"line",@validRows);
catalog(end+1) = makeMetric("aero_balance","aero",["lateral","longitudinal"], ...
    "perSpeed","aero_balance_front",[],"fraction","%",100, ...
    "front aero balance (%)","Aerodynamic balance","Front fraction",false,"line",@validRows);
catalog(end+1) = makeMetric("mechanical_balance","balance","lateral", ...
    "perSpeed","mechanical_balance_front",[],"fraction","%",100, ...
    "mechanical balance (%)","Mechanical balance","Front fraction",false,"line",@validRows);
catalog(end+1) = makeMetric("handling_balance","balance","lateral", ...
    "perSpeed","K_linear_rad_per_mps2",@(T) T.K_linear_rad_per_mps2, ...
    "rad/(m/s^2)","deg/g",9.80665*180/pi, ...
    "K_{linear} (deg/g)","Handling balance","Linear understeer gradient",true,"line",@validRows);
catalog(end+1) = makeMetric("yaw_balance","balance","lateral", ...
    "perSpeed","cuo_steer_linear_rad",@(T) T.cuo_steer_linear_rad, ...
    "rad","deg",180/pi, ...
    "C_{u\delta} (deg)","Yaw balance","Linear steer response",false,"line",@validRows);

catalog(end+1) = makeMetric("front_ride_height","ride",["lateral","longitudinal"], ...
    "perSpeed","front_ride_height_m",[],"m","in",39.37007874015748, ...
    "front ride height (in)","Ride and suspension","Front axle",false,"line",@validRows);
catalog(end+1) = makeMetric("rear_ride_height","ride",["lateral","longitudinal"], ...
    "perSpeed","rear_ride_height_m",[],"m","in",39.37007874015748, ...
    "rear ride height (in)","Ride and suspension","Rear axle",false,"line",@validRows);
catalog(end+1) = makeMetric("front_camber","ride",["lateral","longitudinal"], ...
    "perSpeed","front_camber_rad",@(T) T.front_camber_rad,"rad","deg",180/pi, ...
    "front camber (deg)","Ride and suspension","Front axle",false,"line",@validRows);
catalog(end+1) = makeMetric("rear_camber","ride",["lateral","longitudinal"], ...
    "perSpeed","rear_camber_rad",@(T) T.rear_camber_rad,"rad","deg",180/pi, ...
    "rear camber (deg)","Ride and suspension","Rear axle",false,"line",@validRows);
catalog(end+1) = makeMetric("pitch_angle","ride",["lateral","longitudinal"], ...
    "perSpeed","pitch_rad",[],"rad","deg",180/pi, ...
    "pitch angle (deg)","Ride and suspension","Body pitch",false,"line",@validRows);
catalog(end+1) = makeMetric("front_shock_travel","ride",["lateral","longitudinal"], ...
    "perSpeed","front_shock_travel_m",[],"m","in",39.37007874015748, ...
    "front shock travel (in)","Ride and suspension","Front axle",false,"line",@validRows);
catalog(end+1) = makeMetric("rear_shock_travel","ride",["lateral","longitudinal"], ...
    "perSpeed","rear_shock_travel_m",[],"m","in",39.37007874015748, ...
    "rear shock travel (in)","Ride and suspension","Rear axle",false,"line",@validRows);

catalog(end+1) = makeMetric("front_axle_load","loads",["lateral","longitudinal"], ...
    "perSpeed","Fz_front_axle_N",[],"N","N",1, ...
    "front axle load (N)","Loads and wheel lift","Front axle",false,"line",@validRows);
catalog(end+1) = makeMetric("rear_axle_load","loads",["lateral","longitudinal"], ...
    "perSpeed","Fz_rear_axle_N",[],"N","N",1, ...
    "rear axle load (N)","Loads and wheel lift","Rear axle",false,"line",@validRows);
catalog(end+1) = makeMetric("min_wheel_load","loads",["lateral","longitudinal"], ...
    "perSpeed","min_Fz_N",[],"N","N",1, ...
    "minimum wheel load (N)","Loads and wheel lift","Minimum wheel load",false,"line",@validRows);
catalog(end+1) = makeMetric("wheel_lift","loads",["lateral","longitudinal"], ...
    "perSpeed","wheel_lift",[],"flag","flag",1, ...
    "wheel lift","Loads and wheel lift","Flag",false,"stairs",@allRows);

catalog(end+1) = makeMetric("validity","validity",["lateral","longitudinal"], ...
    "perSpeed","valid",[],"flag","flag",1, ...
    "validity","Validity","Solver validity",false,"stairs",@allRows);
catalog(end+1) = makeMetric("truncated","validity",["lateral","longitudinal"], ...
    "perSpeed","truncated",[],"flag","flag",1, ...
    "truncated","Validity","Ramp truncated",false,"stairs",@allRows);
catalog(end+1) = makeMetric("power_limited","validity",["lateral","longitudinal"], ...
    "perSpeed","power_limited",[],"flag","flag",1, ...
    "power limited","Validity","Power limit active",false,"stairs",@allRows);
catalog(end+1) = makeMetric("aero_outside_map","validity",["lateral","longitudinal"], ...
    "perSpeed","aero_outside_map",[],"flag","flag",1, ...
    "aero outside map","Validity","Aero map status",false,"stairs",@allRows);

catalog(end+1) = makeMetric("raw_aLat","raw","lateral", ...
    "points","aLat_mps2",[],"m/s^2","g",1/9.80665, ...
    "raw a_y (g)","Raw ramp points","Lateral acceleration",false,"markers",@validRows);
catalog(end+1) = makeMetric("raw_aLong","raw","longitudinal", ...
    "points","aLong_mps2",[],"m/s^2","g",1/9.80665, ...
    "raw a_x (g)","Raw ramp points","Longitudinal acceleration",false,"markers",@validRows);
catalog(end+1) = makeMetric("raw_steer","raw","lateral", ...
    "points","steer_rad",[],"rad","deg",180/pi, ...
    "raw steer (deg)","Raw ramp points","Steering",false,"markers",@validRows);
catalog(end+1) = makeMetric("raw_yaw_rate","raw","lateral", ...
    "points","yaw_rate_rps",[],"rad/s","rps",1/(2*pi), ...
    "raw yaw rate (rps)","Raw ramp points","Yaw rate",false,"markers",@validRows);

if isfield(options,'type') && ~isempty(options.type)
    requestedType = lower(string(options.type));
elseif isfield(options,'validType') && ~isempty(options.validType)
    requestedType = lower(string(options.validType));
else
    requestedType = "";
end
if strlength(requestedType) > 0
    keep = arrayfun(@(s) any(s.validTypes == requestedType) || ...
        any(s.validTypes == "any"),catalog);
    catalog = catalog(keep);
end
end

function spec = makeMetric(id,tab,validTypes,sourceLevel,field,derivation, ...
    storedUnits,displayUnits,scale,yLabel,titleText,subtitle,zeroLine,style,validityRule)
spec = metricTemplate();
spec.id = id;
spec.tab = tab;
spec.validTypes = validTypes;
spec.sourceLevel = sourceLevel;
spec.field = field;
spec.derivation = derivation;
spec.storedUnits = storedUnits;
spec.displayUnits = displayUnits;
spec.scale = scale;
spec.yLabel = yLabel;
spec.title = titleText;
spec.subtitle = subtitle;
spec.zeroLine = zeroLine;
spec.seriesStyle = struct('style',string(style),'lineStyle',"-", ...
    'marker',"none",'lineWidth',1.5,'markerSize',6);
spec.validityRule = validityRule;
end

function spec = metricTemplate()
spec = struct('id',"",'tab',"",'validTypes',strings(0,1), ...
    'sourceLevel',"",'field',"",'derivation',[], ...
    'storedUnits',"",'displayUnits',"",'scale',1,'yLabel',"", ...
    'title',"",'subtitle',"",'zeroLine',false,'seriesStyle',struct(), ...
    'validityRule',@validRows);
end

function mask = validRows(T)
if istable(T) && ismember('valid',T.Properties.VariableNames)
    mask = logical(T.valid);
else
    mask = true(height(T),1);
end
mask = mask(:);
end

function mask = allRows(T)
mask = true(height(T),1);
end
