function metadata = serializeSolverProfile(profile)
%SERIALIZESOLVERPROFILE Return stable, JSON-compatible profile metadata.

profile = rampSpeed.resolveSolverProfile(profile);
metadata = struct( ...
    "id",string(profile.id), ...
    "label",string(profile.label), ...
    "version",double(profile.version), ...
    "solverOptions",profile.solverOptions, ...
    "aeroMode",string(profile.aeroMode), ...
    "powertrainModel",string(profile.powertrainModel), ...
    "approximate",logical(profile.approximate), ...
    "description",string(profile.description));
end
