function profiles = solverProfiles()
%SOLVERPROFILES Return the supported ramp-speed solver configurations.
%
% The accurate profile preserves the existing longitudinal optimizer
% settings. Preview profiles trade solver effort and, for the approximate
% profile, ride-height aero fidelity for shorter runs.

profiles = [ ...
    makeProfile("accurate","Accurate",2000,1e-2,1e-10, ...
        "coupled",false, ...
        "Full ride-height aero with the existing solver tolerances."), ...
    makeProfile("fastPreview","Fast preview",1000,1e-2,1e-8, ...
        "coupled",false, ...
        "Reduced optimizer budget with ride-height aero retained."), ...
    makeProfile("approximateAeroPreview","Approximate aero preview", ...
        1000,1e-2,1e-8,"static",true, ...
        "Reduced optimizer budget using static aero instead of the coupled ride-height solve.") ...
    ];
end

function profile = makeProfile(id,label,maxEvaluations, ...
        constraintTolerance,stepTolerance,aeroMode,approximate,description)
profile = struct( ...
    "id",id, ...
    "label",label, ...
    "version",1, ...
    "solverOptions",struct( ...
        "maxFunctionEvaluations",maxEvaluations, ...
        "constraintTolerance",constraintTolerance, ...
        "stepTolerance",stepTolerance, ...
        "display","off"), ...
    "aeroMode",aeroMode, ...
    "powertrainModel","continuousEnvelope", ...
    "approximate",approximate, ...
    "description",description);
end
