function car = buildCarFromParameterSet(q,driverWeight,aero,powertrain,tire, ...
    rideHeightAero,camberKinematics,R_sf)
%BUILDCARFROMPARAMETERSET Construct one solver-ready Car from resolved inputs.
%   This is the shared constructor used by the legacy parameter loop and the
%   ramp-speed single-car factory. It does not create a car catalog.

required = {'mass','wheelbase','weight_dist','track_width','wheel_radius', ...
    'cg_height','roll_center_height_front','roll_center_height_rear', ...
    'I_zz','gamma_f','gamma_r','camber_compliance_f', ...
    'camber_compliance_r','ackermann','static_r_toe', ...
    'grip_scaling_front','grip_scaling_rear','I_wheel','I_driveline','Crr'};
for i = 1:numel(required)
    if ~isfield(q,required{i})
        error('buildCarFromParameterSet:missingField', ...
            'Resolved car parameters are missing %s.',required{i});
    end
end

car = Car(q.mass+driverWeight,q.wheelbase,q.weight_dist, ...
    q.track_width,q.wheel_radius,q.cg_height, ...
    q.roll_center_height_front,q.roll_center_height_rear,R_sf,q.I_zz, ...
    q.gamma_f,q.gamma_r,q.camber_compliance_f,q.camber_compliance_r, ...
    aero,powertrain,tire,q.ackermann,q.static_r_toe, ...
    q.grip_scaling_front,q.grip_scaling_rear,q.I_wheel,q.I_driveline, ...
    q.Crr,rideHeightAero,camberKinematics);
end
