function C = doePlotCatalog()
%DOEPLOTCATALOG Recommended figures for design-phase DOE communication.
id = {'quality';'sensitivity';'main_effects';'interactions'; ...
    'pareto_events';'pareto_energy';'correlation';'speed_grip'; ...
    'balance';'validation'};
title = {'Simulation quality';'Ranked sensitivities';'Main effects'; ...
    'Parameter interactions';'Event Pareto';'Lap time vs energy'; ...
    'Input/output correlation';'Capability vs speed'; ...
    'Mechanical vs aero balance';'Predicted vs simulated'};
purpose = { ...
    'Valid cases, envelope coverage, wheel lift, and event distributions'; ...
    'Ranks parameters by normalized effect on each selected response'; ...
    'Shows response curvature and practical change across each input range'; ...
    'Shows whether two design variables amplify or oppose each other'; ...
    'Shows tradeoffs among autocross, acceleration, and skidpad time'; ...
    'Shows performance gained per unit of simulated tractive work'; ...
    'Screens relationships and collinearity before interpreting regressions'; ...
    'Compares lateral, acceleration, and braking capability at 10/20/30 m/s'; ...
    'Shows speed-dependent balance tendency and wheel-load margin'; ...
    'Checks surrogate bias, outliers, and residual spread'};
producer = {'plotDOEMetrics';'DOE_Fitting';'DOE_Fitting';'DOE_Fitting'; ...
    'plotDOEMetrics';'plotDOEMetrics';'plotDOEMetrics';'plotDOEMetrics'; ...
    'plotDOEMetrics';'DOE_Fitting'};
default_enabled = [true;true;true;false;true;true;true;true;true;true];
C = table(id,title,purpose,producer,default_enabled);
end
