function [score,breakdown] = doeScoreCase(points,row,cfg)
%DOESCORECASE Apply configured DOE penalties to supplied event points.

modeled = points.total;
penaltyInvalid = (~row.valid) * cfg.penalties.invalidCase.fixedPoints;
penaltySolve = enabledMetricPenalty(cfg.penalties.solveFailure,row, ...
    'solve_failure_fraction', ...
    @(x,p) p.pointsPerFraction * max(x-p.thresholdFraction,0));
penaltyWheelLift = enabledMetricPenalty(cfg.penalties.wheelLift,row,'min_Fz_N', ...
    @(x,p) p.pointsPerN * max(p.threshold_N-x,0));
penaltyEnergy = enabledMetricPenalty(cfg.penalties.energy,row,'total_work_kJ', ...
    @(x,p) p.pointsPerKJ * max(x-p.threshold_kJ,0));
penaltyUndersteer = enabledMetricPenalty(cfg.penalties.understeer,row, ...
    cfg.penalties.understeer.metric, ...
    @(x,p) p.pointsPerDegPerG * outsideBand(x,p.lower_deg_per_g,p.upper_deg_per_g));
penaltyRebalance = enabledMetricPenalty(cfg.penalties.rebalance,row, ...
    'rebalance_speed_mps', ...
    @(x,p) p.pointsPerMps * abs(x-p.target_mps));

totalPenalty = penaltyInvalid + penaltySolve + penaltyWheelLift + penaltyEnergy + ...
    penaltyUndersteer + penaltyRebalance;
score = modeled-totalPenalty;
breakdown = struct( ...
    'points_skidpad',points.skidpad, ...
    'points_accel',points.accel, ...
    'points_autocross',points.autocross, ...
    'points_endurance',points.endurance, ...
    'modeled_dynamic_points',modeled, ...
    'penalty_invalid_case',penaltyInvalid, ...
    'penalty_solve_failure',penaltySolve, ...
    'penalty_wheel_lift',penaltyWheelLift, ...
    'penalty_energy',penaltyEnergy, ...
    'penalty_understeer',penaltyUndersteer, ...
    'penalty_rebalance',penaltyRebalance, ...
    'total_penalty_points',totalPenalty, ...
    'objective_score',score);
end

function penalty = enabledMetricPenalty(config,row,metricName,calculator)
if ~config.enabled
    penalty = 0;
    return
end
metric = row.(metricName);
if ~isfinite(metric)
    penalty = NaN;
else
    penalty = calculator(metric,config);
end
end

function distance = outsideBand(value,lower,upper)
if value < lower
    distance = lower-value;
elseif value > upper
    distance = value-upper;
else
    distance = 0;
end
end
