function study = DOEStudyConfig()
%DOESTUDYCONFIG User-editable settings and ranges for an adaptive DOE study.

study.name = "vehicle_design_2026";
study.mode = "sensitivity";
study.randomSeed = 1;
study.initialCases = 128;
study.batchSize = 64;
study.maxCases = 512;
study.numWorkers = 16;
study.allowSerialFallback = false;
study.resume = true;
study.parameters = table( ...
    ["mass";"wheelbase";"weight_dist";"track_width";"cg_height"; ...
     "R_sf";"accel_cda";"accel_cla";"final_drive"; ...
     "gamma_f";"gamma_r";"p_i"], ...
    [-5;-5;-5;-5;-10;-15;-15;-15;-8;-2;-2;-10], ...
    [ 5; 5; 5; 5; 10; 15; 15; 15; 8; 0; 0; 10], ...
    [repmat("percent",9,1);"absolute";"absolute";"percent"], ...
    'VariableNames',{'name','lower','upper','rangeType'});
study.adaptive = struct('responses', ...
    {{'modeled_dynamic_points','t_autox','t_accel','t_skid', ...
      'total_work_kJ','understeer_gradient_10_deg_per_g', ...
      'understeer_gradient_25_deg_per_g'}}, ...
    'hybridSensitivityFraction',0.70,'candidatePoolSize',20000, ...
    'minimumDistance',0.03,'kernel','ardmatern32');
study.events = ["skidpad","accel","autocross","endurance"];
study.ramps = struct('enabled',true,'speeds',[10 25],'nRamp',8, ...
    'nBisect',3,'mode','balanced','saveFullPoints',false);
study.output = struct('directory',fullfile(fileparts(which('DOEStudyConfig')), ...
    'DOE_output'),'checkpoint','DOE_checkpoint.mat', ...
    'results','DOE_results.mat','analysis','DOE_analysis.mat');
study.objective = defaultObjective();
end

function objective = defaultObjective()
objective.primary = "modeled_dynamic_points";
objective.penalties.invalidCase = struct( ...
    'enabled',true,'fixedPoints',575);
objective.penalties.solveFailure = struct( ...
    'enabled',false,'thresholdFraction',0,'pointsPerFraction',0);
objective.penalties.wheelLift = struct( ...
    'enabled',false,'threshold_N',0,'pointsPerN',0);
objective.penalties.energy = struct( ...
    'enabled',false,'threshold_kJ',Inf,'pointsPerKJ',0);
objective.penalties.understeer = struct( ...
    'enabled',false,'lower_deg_per_g',-Inf,'upper_deg_per_g',Inf, ...
    'pointsPerDegPerG',0,'metric',"understeer_gradient_25_deg_per_g");
objective.penalties.rebalance = struct( ...
    'enabled',false,'target_mps',NaN,'pointsPerMps',0);
end
